# Generated by Django 6.0.4 on 2026-04-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bucketdepositconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='注销日期'),
        ),
    ]
